courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.course_list, name='list'), #add name for url
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),
]

learning_site/urls.py
from django.conf.urls import include, url #don't forget to import include!
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns #tells django/python how to serve static files

from . import views #import views file

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')), #include('courses.urls', namespace='course') to namespace a group of URLs
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page), #takes 5 arguments(pattern, view to send request to, keyword argument for view, route name, prefix) #
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model): #extend from base Model class
    created_at = models.DateTimeField(auto_now_add = True)
    title = models.CharField(max_length = 255)
    description = models.TextField()

    def __str__(self): #to configure how python shell returns queries
        return self.title


class Step(models.Model):
    title = models.CharField(max_length = 255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    content = models.TextField(blank = True, default = "")

    class Meta:
        ordering = ['order',]   #handles ordering

    def __str__(self):
        return ('{}: {}'.format(self.order, self.title))

courses/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render #for using templates, get_object_or_404 is for handling 404s

from .models import Course, Step #imports from models.py
# Create your views here.
def course_list(request):
    courses = Course.objects.all() #selects all courses that exist
    return render(request, 'courses/course_list.html', {'courses': courses}) #takes 3 arguments - request, template to render, optional context dictionary

def course_detail(request, pk):
    #course = Course.objects.get(pk = pk) pk is primary key/id, don't need now because of 404
    course = get_object_or_404(Course, pk = pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id = course_pk, pk = step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/views.py
# from django.http import HttpResponse

from django.shortcuts import render #changed to import render from import HttpResponse after adding template folder

def home_page(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %}{{course.title}} {% endblock %}

{% block content%}
<article class="">
  <h2>{{ course.title }}</h2>
  {{ course.description}}

  <p> There are {{ course.step_set.count }} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", "}}</p>
  <section>
    {% for step in course.step_set.all %}
      <h3><a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{step.title}}</a></h3>
        {{step.description}}
    {% endfor %}

  </section>

</article>
{% endblock%}

courses/templates/courses/course_list.html
{% extends 'layout.html' %}
{% load static from staticfiles %}

<!-- add app specific css to static block in app templates -->
{% block static %}<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}"> {% endblock %}
{% block title %} Available Courses {% endblock %}


{% block content %}
<div class="cards">
  {% for course in courses %}
  <div class="card">
    <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title}}</a></header>
      <div class="card-copy">
        {{ course.description }}
      </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

courses/templates/courses/step_detail.html
{% extends 'layout.html' %}

{% block title %} {{step.title}} - {{step.course.title }} {% endblock %}

{% block content %}
  <article class="">
    <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{step.course.title}}</a></h2>
        <h3>{{step.title}}</h3>
        {{ step.content|linebreaks }}

  </article>

{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %} Welcome! {% endblock %}

{% block content %}
  <h1>Welcome to Learning Site</h1>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <!-- need to add static block for app specific css -->
    {% block static %} {% endblock %}
  </head>
  <body>
    <div class="site-container">
      <nav>
        <a href="{% url 'views.home_page' %}">Home</a>
        <!-- note use of namespaces in link below; {% url 'courses:list' %} to link to a named and namespaced URL -->
        <a href="{%url 'courses:list'%}">Courses</a>
      </nav>
      {% block content %} {% endblock %}
    </div>

  </body>
</html>